#!/usr/bin/env python3
"""build-skill-resources.py — assemble the boat-day skill bundle from KB notes.

The boat-day skill's job is to run `planning/day-plan-protocol.md`. Its bundled
knowledge is the **decision layer** of this KB — conditions, seasonal priors,
the species routers (the situation→technique map), locations, the day-plan
protocol, and the gear-class lexicon — plus **one profile** so recommendations
resolve to owned gear. Execution detail (techniques, lures, rigging) stays one
link away in the repo and is fetched on demand.

Usage:
    python scripts/build-skill-resources.py                 # default: profiles/cameron
    python scripts/build-skill-resources.py --profile profiles/_template
    python scripts/build-skill-resources.py --no-profile    # generic, class-term only

A generic build (no profile) still produces a working skill: the day-plan
protocol degrades to class-term recommendations.
"""
from __future__ import annotations

import argparse
import shutil
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
SKILL_DIR = ROOT / "skills" / "boat-day"
RES = SKILL_DIR / "resources"

# The decision layer bundled into the skill (relative to repo root).
KNOWLEDGE_DIRS = ["planning", "conditions", "seasonal", "locations", "species"]
KNOWLEDGE_FILES = ["tackle/gear-classes.md"]


def copy_note(src: Path, dst: Path) -> None:
    dst.parent.mkdir(parents=True, exist_ok=True)
    shutil.copy2(src, dst)


def build(profile: Path | None) -> int:
    if RES.exists():
        shutil.rmtree(RES)
    kb = RES / "knowledge"
    kb.mkdir(parents=True, exist_ok=True)

    count = 0
    for d in KNOWLEDGE_DIRS:
        srcdir = ROOT / d
        if not srcdir.is_dir():
            continue
        for p in sorted(srcdir.glob("*.md")):
            copy_note(p, kb / d / p.name)
            count += 1
    for f in KNOWLEDGE_FILES:
        p = ROOT / f
        if p.exists():
            copy_note(p, kb / f)
            count += 1

    # Profile
    profile_status = "none (generic — class-term recommendations only)"
    if profile is not None:
        if not profile.is_dir():
            print(f"error: profile dir not found: {profile}", file=sys.stderr)
            return 2
        pdst = RES / "profile"
        pdst.mkdir(parents=True, exist_ok=True)
        pfiles = 0
        for p in sorted(profile.glob("*.md")):
            copy_note(p, pdst / p.name)
            pfiles += 1
        profile_status = f"{profile.name} ({pfiles} files)"

    # INDEX + SKILL.md
    (RES / "INDEX.md").write_text(
        "# Boat-Day Skill — bundled resources\n\n"
        "Generated by `scripts/build-skill-resources.py` from the KB decision "
        "layer. Do not edit by hand — re-run the script.\n\n"
        f"- knowledge notes bundled: **{count}**\n"
        f"- profile: **{profile_status}**\n\n"
        "Bundled: " + ", ".join(f"`{d}/`" for d in KNOWLEDGE_DIRS) +
        ", `tackle/gear-classes.md`. Execution detail (techniques, lures, "
        "rigging) is fetched from the repo on demand.\n",
        encoding="utf-8",
    )
    write_skill_md(profile is not None)
    print(
        f"OK: bundled {count} knowledge notes; profile = {profile_status}\n"
        f"  -> {RES.relative_to(ROOT)}"
    )
    return 0


def write_skill_md(has_profile: bool) -> None:
    profile_line = (
        "A profile is bundled under `resources/profile/` — resolve gear classes "
        "to the owned rods/reels/lures and respect the boat envelope."
        if has_profile
        else "No profile is bundled — give **class-term** recommendations "
        "(e.g. 'surface-iron class, 40-60 lb') and note that adding a profile "
        "sharpens them."
    )
    SKILL_DIR.mkdir(parents=True, exist_ok=True)
    (SKILL_DIR / "SKILL.md").write_text(
        "---\n"
        "name: boat-day\n"
        "description: Plan a SoCal/Baja fishing day — pull conditions, apply "
        "seasonal priors and interpretation layers, route species to technique, "
        "and resolve gear against a profile.\n"
        "---\n\n"
        "# Boat-Day Planner\n\n"
        "Follow `resources/knowledge/planning/day-plan-protocol.md` step by "
        "step. It consumes **BightSST** (live conditions) and **this KB** "
        "(knowledge) at plan time.\n\n"
        "1. Pull conditions from BightSST (per zone + along the route, observed "
        "and forecast).\n"
        "2. Apply `resources/knowledge/seasonal/` priors and "
        "`resources/knowledge/conditions/` layers.\n"
        "3. Enter the `resources/knowledge/species/` routers to map situation → "
        "technique → gear class.\n"
        "4. Resolve gear. " + profile_line + "\n\n"
        "Class terms resolve via "
        "`resources/knowledge/tackle/gear-classes.md`.\n",
        encoding="utf-8",
    )


def main() -> int:
    ap = argparse.ArgumentParser(description="Build the boat-day skill bundle.")
    ap.add_argument(
        "--profile",
        default="profiles/cameron",
        help="profile dir to bundle (default: profiles/cameron)",
    )
    ap.add_argument(
        "--no-profile",
        action="store_true",
        help="build a generic skill with no profile (class-term recommendations)",
    )
    args = ap.parse_args()
    profile = None if args.no_profile else (ROOT / args.profile)
    return build(profile)


if __name__ == "__main__":
    raise SystemExit(main())
