#!/usr/bin/env python3
"""link-maintenance.py — the hard-habit maintenance pass for the KB.

Run before EVERY commit:

    python scripts/link-maintenance.py

It does four things:
  (a) validates every relative markdown link resolves — EXITS NONZERO on any
      dead link;
  (b) regenerates each note's `## Linked from` backlinks section idempotently
      between <!-- backlinks:start --> / <!-- backlinks:end --> markers;
  (c) regenerates each directory's README.md index between
      <!-- index:start --> / <!-- index:end --> markers (curated prose outside
      the markers is preserved);
  (d) writes a capped Mermaid map of a branch's intra-folder note connections
      between <!-- mermaid:start --> / <!-- mermaid:end --> markers on each
      branch README (skipped, with a note, if the branch exceeds the node cap).

The script is deterministic: a second run with no editorial changes produces no
diff.
"""
from __future__ import annotations

import os
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
MERMAID_NODE_CAP = 30

# Files never processed at all (raw inputs + top-level spec doc + generated skill).
EXCLUDE_FULL = {
    ROOT / "CLAUDE.md",
    ROOT / "sources" / "memory-export.md",
    ROOT / "sources" / "bd-transcript-knowledge-proposal.md",
    ROOT / "sources" / "spot-lists.md",
    ROOT / "skills" / "boat-day" / "SKILL.md",  # generated by build-skill-resources.py
}
# Directories whose markdown is raw or generated and never linked into the graph.
EXCLUDE_DIRS = {
    ROOT / ".git",
    ROOT / "sources" / "transcripts",
    ROOT / "skills" / "boat-day" / "resources",  # generated skill bundle
}

LINK_RE = re.compile(r"\[([^\]]*)\]\(([^)]+)\)")
H1_RE = re.compile(r"^#\s+(.*?)\s*$", re.MULTILINE)

BACKLINK_START = "<!-- backlinks:start -->"
BACKLINK_END = "<!-- backlinks:end -->"
INDEX_START = "<!-- index:start -->"
INDEX_END = "<!-- index:end -->"
MERMAID_START = "<!-- mermaid:start -->"
MERMAID_END = "<!-- mermaid:end -->"


def is_excluded(path: Path) -> bool:
    if path in EXCLUDE_FULL:
        return True
    for d in EXCLUDE_DIRS:
        if d in path.parents:
            return True
    return False


def all_markdown() -> list[Path]:
    out = []
    for p in ROOT.rglob("*.md"):
        if is_excluded(p):
            continue
        out.append(p)
    return sorted(out)


def title_of(path: Path) -> str:
    """First H1, else a title-cased filename."""
    try:
        text = path.read_text(encoding="utf-8")
    except OSError:
        return path.stem
    m = H1_RE.search(strip_front_matter(text))
    if m:
        return m.group(1).strip()
    return path.stem.replace("-", " ").title()


def strip_front_matter(text: str) -> str:
    if text.startswith("---\n"):
        end = text.find("\n---", 4)
        if end != -1:
            nl = text.find("\n", end + 1)
            return text[nl + 1 :] if nl != -1 else ""
    return text


def summary_of(path: Path) -> str:
    """First real paragraph (lines joined), trimmed to one sentence-ish."""
    text = strip_front_matter(path.read_text(encoding="utf-8"))
    para: list[str] = []
    for line in text.splitlines():
        s = line.strip()
        skip = (
            not s
            or s.startswith("#")
            or s.startswith("<!--")
            or s.startswith(">")
            or s.startswith("|")
            or s.startswith("-")
            or s.startswith("*")
            or s.startswith("```")
        )
        if para and (not s or skip):
            break  # end of the first paragraph
        if skip:
            continue
        para.append(s)
    if not para:
        return ""
    joined = re.sub(r"\[([^\]]+)\]\([^)]+\)", r"\1", " ".join(para))  # strip links
    joined = re.sub(r"\*\*|`", "", joined)  # drop bold/code marks
    m = re.match(r"(.{0,160}?[.!?])(\s|$)", joined)
    return (m.group(1) if m else joined[:160]).strip()


def parse_links(path: Path):
    """Yield (link_text, file_part, raw_target) for each relative link."""
    text = path.read_text(encoding="utf-8")
    for m in LINK_RE.finditer(text):
        text_part, target = m.group(1), m.group(2).strip()
        # strip optional title:  path "Title"
        target = target.split(" ", 1)[0].strip()
        if target.startswith(("http://", "https://", "mailto:", "#")):
            continue
        file_part = target.split("#", 1)[0]
        if not file_part:
            continue
        yield text_part, file_part, target


def replace_block(text: str, start: str, end: str, body: str) -> str:
    """Replace content between start/end markers (inclusive) with markers+body.
    Appends a fresh block at EOF if the markers are absent."""
    block = f"{start}\n{body}\n{end}"
    if start in text and end in text:
        pre = text[: text.index(start)]
        post = text[text.index(end) + len(end) :]
        return pre + block + post
    sep = "" if text.endswith("\n\n") else ("\n" if text.endswith("\n") else "\n\n")
    return text + sep + "\n" + block + "\n"


def main() -> int:
    md_files = all_markdown()
    readmes = [p for p in md_files if p.name == "README.md"]
    extraction_log = ROOT / "sources" / "extraction-log.md"
    note_files = [
        p for p in md_files if p.name != "README.md" and p != extraction_log
    ]

    # ---- (a) validate links + build note->note graph ----
    dead: list[str] = []
    inbound: dict[Path, set[Path]] = {p: set() for p in note_files}
    for src in md_files:
        for _text, file_part, raw in parse_links(src):
            target = (src.parent / file_part).resolve()
            if not target.exists():
                dead.append(f"{src.relative_to(ROOT)} -> {raw}")
                continue
            # record editorial note->note backlinks (README/log excluded as source)
            if (
                src in note_files
                and target in inbound
                and target != src
            ):
                inbound[target].add(src)

    # ---- (b) regenerate backlinks on every note ----
    for note in note_files:
        srcs = sorted(inbound[note], key=lambda p: title_of(p).lower())
        if srcs:
            lines = ["## Linked from", ""]
            for s in srcs:
                rel = os.path.relpath(s, note.parent)
                lines.append(f"- [{title_of(s)}]({rel})")
            body = "\n".join(lines)
        else:
            body = "## Linked from\n\n_Nothing links here yet._"
        text = note.read_text(encoding="utf-8")
        new = replace_block(text, BACKLINK_START, BACKLINK_END, body)
        if new != text:
            note.write_text(new, encoding="utf-8")

    # ---- (c)+(d) directory READMEs: index + mermaid ----
    # group notes by directory
    dirs = sorted({p.parent for p in note_files})
    for d in dirs:
        readme = d / "README.md"
        dir_notes = sorted(
            [p for p in note_files if p.parent == d], key=lambda p: p.name
        )
        subdirs = sorted(
            {p.parent for p in note_files if d in p.parents and p.parent != d}
        )
        # direct child subdirs only
        child_dirs = sorted({sd for sd in subdirs if sd.parent == d})

        # index body
        idx = ["## Index", ""]
        for n in dir_notes:
            summ = summary_of(n)
            tail = f" — {summ}" if summ else ""
            idx.append(f"- [{title_of(n)}]({n.name}){tail}")
        if child_dirs:
            idx.append("")
            idx.append("### Subfolders")
            for cd in child_dirs:
                idx.append(f"- [{cd.name}/]({cd.name}/README.md)")
        index_body = "\n".join(idx)

        # mermaid body (intra-folder edges only)
        node_ids = {n: f"n{i}" for i, n in enumerate(dir_notes)}
        edges = []
        for n in dir_notes:
            for _t, file_part, _raw in parse_links(n):
                tgt = (n.parent / file_part).resolve()
                if tgt in node_ids and tgt != n:
                    edges.append((node_ids[n], node_ids[tgt]))
        edges = sorted(set(edges))
        if len(dir_notes) > MERMAID_NODE_CAP:
            mer_body = (
                f"## Map\n\n_Map skipped: {len(dir_notes)} notes exceed the "
                f"{MERMAID_NODE_CAP}-node cap._"
            )
        elif not edges:
            mer_body = "## Map\n\n_No intra-folder links yet._"
        else:
            lines = ["## Map", "", "```mermaid", "graph LR"]
            for n in dir_notes:
                label = title_of(n).replace('"', "'")
                lines.append(f'  {node_ids[n]}["{label}"]')
            for a, b in edges:
                lines.append(f"  {a} --> {b}")
            lines.append("```")
            mer_body = "\n".join(lines)

        if readme.exists():
            text = readme.read_text(encoding="utf-8")
        else:
            title = d.name.replace("-", " ").title() if d != ROOT else "Index"
            text = f"# {title}\n\n"
        text = replace_block(text, INDEX_START, INDEX_END, index_body)
        text = replace_block(text, MERMAID_START, MERMAID_END, mer_body)
        readme.write_text(text, encoding="utf-8")

    # ---- report ----
    if dead:
        print("DEAD LINKS:", file=sys.stderr)
        for d_ in sorted(set(dead)):
            print(f"  {d_}", file=sys.stderr)
        print(f"\n{len(set(dead))} dead link(s).", file=sys.stderr)
        return 1
    print(
        f"OK: {len(note_files)} notes, {len(readmes) + len(dirs)} indexes, "
        "0 dead links."
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
